### ISSUE TITLE
For the product page , where there are more than 4 thumbnail images we can add the slider it will be much better.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#11]
**The url:**
https://vibejewellery.com/products/20g-9k-yellow-gold-cz-prong-setting-nose-stud?_pos=1&_sid=64df590d6&_ss=r&variant=40064010059869
**Actual result:**
For the product page , where there are more than 4 thumbnail images we can add the slider it will be much better.
![image](https://user-images.githubusercontent.com/102131636/166877829-14c3ea50-007f-4d26-a991-b85fb7b98237.png)

**Expected result:**
The sliders are missing for the thumnails images more than 4.

**Comment by ui-amansingh** [comment]
Slider has already been added please check.
When we click on the thumbnail image, the image scroll automatically. 
![image](https://user-images.githubusercontent.com/100340062/166888488-5e292f98-cfe7-4f07-ac3a-b21b65f32789.png)

**Comment by sudhanshu0603** [comment]
ok, fine
