### ISSUE TITLE
For some of the collections , the filters are not added.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#12]
**The url:**
https://vibejewellery.com/collections/piercing-jewelry
https://vibejewellery.com/collections/new-arrivals
**Actual result:**
For some of the collections , the filters are not added.
![image](https://user-images.githubusercontent.com/102131636/166878905-f1419418-63e8-45e4-980f-c0c918673d05.png)
**Expected result:**
The filters can be added.
![image](https://user-images.githubusercontent.com/102131636/166879064-6e0eb388-6fdc-4b0d-ab5b-949b1bf7abd6.png)

**Comment by dev-amitkumarbharti1** [comment]
In this collection product is more than 1000 product and if a product have more than 1000 product then filter will not come for that collection

**Comment by sudhanshu0603** [comment]
ok , fine
