### ISSUE TITLE
For color swatches the images are added in the product page.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#13]
**The url:**
https://vibejewellery.com/products/heart-crystal-logo-with-epoxy-cover-ss-ear-stud-earring?_pos=1&_fid=b9376d41b&_ss=c&variant=40063864111197
**Actual result:**
For color swatches the images are added in the product page.
![image](https://user-images.githubusercontent.com/102131636/166881405-5d26245e-5bfb-42c8-97b2-29a5aa3e9dce.png)

**Expected result:**
The color swatches the images should not be added.

**Comment by dev-amitkumarbharti1** [comment]
There is no standard color for the product that's why added the variants images

**Comment by dev-amitkumarbharti1** [comment]
![image](https://user-images.githubusercontent.com/92047050/166906320-6dcc0bfc-b72a-4a5f-b1ef-ffc4c6525cc3.png)

**Comment by dev-amitkumarbharti1** [comment]
![image](https://user-images.githubusercontent.com/92047050/166906386-45ca5f50-88cc-4bd0-9554-09f6364ee7c8.png)

**Comment by dev-amitkumarbharti1** [comment]
there is no standard color that's why added variants images

**Comment by dev-amitkumarbharti1** [comment]
https://vibejewellery.com/products/heart-crystal-logo-with-epoxy-cover-ss-ear-stud-earring?_pos=1&_fid=b9376d41b&_ss=c&variant=40063864111197

You can check the option values color

**Comment by sudhanshu0603** [comment]
ok ,resolved
