### ISSUE TITLE
The login page, the password and forgot password is coming inside the input field.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#14]
**Actual result:**
The login page, the password and forgot password is coming inside the input field.
![image](https://user-images.githubusercontent.com/102131636/166883035-3cf75131-96d9-4f2c-b6b6-d93b66b8c9f4.png)

**Expected result:**
The forgot password can be aligned below the input field of the password.

**Comment by ui-amansingh** [comment]
fixed

**Comment by sudhanshu0603** [comment]
ok, resolved
