### ISSUE TITLE
The social media links are not added on the footer.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#2]
**Actual result:**
The social media links are not added on the footer.
![image](https://user-images.githubusercontent.com/102131636/166868352-81a73510-476d-4e27-baf7-6f603e21d08a.png)

**Expected result:**
The social media links have to be linked

**Comment by dev-amitkumarbharti1** [comment]
Not provided by the client as this is already added in the requirement form that client will provide links later

**Comment by sudhanshu0603** [comment]
ok, fine
