### ISSUE TITLE
Missing contact details

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#20]
The contact details are missing from the contact page.
https://mk5v7zhejye2wypa-57670664285.shopifypreview.com/pages/contact
![image](https://user-images.githubusercontent.com/97726944/170426007-b1d56354-bc57-4143-9ef3-1f1b2c4237af.png)

**Comment by ui-amansingh** [comment]
Contact details already mentioned in footer.
