### ISSUE TITLE
When we are tying the email in the newsletter then the placeholder test and arrow button is not coming properly.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#3]
**Actual result:**
When we are tying the email in the newsletter then the placeholder test and arrow button is not coming properly.
![image](https://user-images.githubusercontent.com/102131636/166868570-cf13ec17-fb2f-49b1-a1d7-0a7cc7fc6f00.png)

**Expected result:** 
The newsletter can be improved.

**Comment by ui-amansingh** [comment]
fixed
