### ISSUE TITLE
Payment icon size in cart page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#30]
The payment icon is coming small in cart page, we can increase the size.
![image](https://user-images.githubusercontent.com/97726944/170432370-40e5c755-f185-4f1f-9cf9-f115c23fcb5d.png)

**Comment by ui-amansingh** [comment]
Image size is already full size if we increase the size the will become blurry.
