### ISSUE TITLE
The unordered list can be removed from the policy of billing terms and conditons.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#4]
**Actual result:**
The unordered list can be removed from the policy of billing terms and conditions.
![image](https://user-images.githubusercontent.com/102131636/166869235-dc7bdf88-c459-42b6-8b37-edbba77b5bd8.png)

**Expected result:**
The ul tag can be removed from the content.

**Comment by dev-amitkumarbharti1** [comment]
no need to remove the ul tag it will break the footer structure

**Comment by sudhanshu0603** [comment]
ok ,fine
