### ISSUE TITLE
Multiple collections with same image

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#44]
Multiple collections are having same collection images in collection page.
https://mk5v7zhejye2wypa-57670664285.shopifypreview.com/collections
Video: https://www.awesomescreenshot.com/video/9110429?key=cf54055091df3ad5c29f6164e017041f

**Comment by ui-amansingh** [comment]
all collection images coming from backend.
