### ISSUE TITLE
Different products in collection pages

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#45]
The finger ring collection page is having nose ring products. same in lips & tongue collection page.
https://sol4rseg5u4u7rhr-57670664285.shopifypreview.com/collections/finger-rings
https://sol4rseg5u4u7rhr-57670664285.shopifypreview.com/collections/lips
https://sol4rseg5u4u7rhr-57670664285.shopifypreview.com/collections/tongue-piercing
Video: https://www.awesomescreenshot.com/video/9127830?key=6f5cfa28bf2a33f5991e9a149a43b5ce

**Comment by dev-amitkumarbharti1** [comment]
All product and collections is imported directly from his magneto site all collection is already imported through app
