### ISSUE TITLE
Extra white spacing in multiple variants product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#46]
https://vibejewellery.com/products/10mm-pink-base-bioflex-with-crystal-ferido-top-ball-pregnancy-belly-ring?variant=40063977586781
We can reduce the spacing between the title & quantity selectors.
![image](https://user-images.githubusercontent.com/97726944/170695269-97094a6a-7efd-425b-96f2-540fa0fc7cb4.png)

**Comment by ui-amansingh** [comment]
I've managed some white space.
