### ISSUE TITLE
Discount chart is reflecting in product page with Typo error

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#49]
The Discount chart is reflecting in speed worked site but in live site there is no chart present in it.
Preview: https://n35lxf5q19ywtn2r-57670664285.shopifypreview.com/products/20g-surgical-steel-ferido-ball-jeweled-nose-screw-stud-black-diamond
![image](https://user-images.githubusercontent.com/97726944/174286899-b73dc429-5824-4ccf-8a1b-3b6ff1c3c227.png)

Live: https://vibejewellery.com/products/20g-surgical-steel-ferido-ball-jeweled-nose-screw-stud-black-diamond
![image](https://user-images.githubusercontent.com/97726944/174286794-35ff0e62-26ed-40a3-9dfc-e5fb1a9ba5ab.png)

**Comment by Ataurrahman-khan** [comment]
both live and preview theme is same @Shoaibans sir please recheck

**Comment by Shoaibans** [comment]
> both live and preview theme is same @Shoaibans sir please recheck

Ok @Ataurrahman-khan But pls fix the typo error "Quantity"
![image](https://user-images.githubusercontent.com/97726944/174519786-822d7fd3-b461-46a0-bc54-58520973155b.png)
