### ISSUE TITLE
In create account be can add the basic validation for all the input fields.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#5]
**Actual result:**
In create account be can add the basic validation for all the input fields.
![image](https://user-images.githubusercontent.com/102131636/166873857-5efc0a1e-000f-4507-acad-65f27c6df938.png)

**Expected result:**
The basic validation we can add.

**Comment by dev-amitkumarbharti1** [comment]
Basic validation is already added on create account page using form attributes

**Comment by sudhanshu0603** [comment]
ok, fine
