### ISSUE TITLE
When we are not login and clicking on the hambergur then there is a link is coming of account. But it must be the login before are not login as we have login then it must show account.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#7]
**Actual result:**
When we are not login and clicking on the hambergur then there is a link is coming of account. But it must be the login before are not login as we have login then it must show account.
![image](https://user-images.githubusercontent.com/102131636/166875433-f0812e50-a16f-47cc-b8d9-775c2de4af04.png)

**Expected result:**
But it must be the login before are not login as we have login then it must show account.

**Comment by dev-amitkumarbharti1** [comment]
On clicking on the account icon it will redirect to the login page if the customer is not logged in otherwise it will goto to the cart page. It is understood by icon no need to change the text

**Comment by sudhanshu0603** [comment]
ok, fine
