### ISSUE TITLE
The text Policy have to be in uppercase, for some of the policies it is coming in lower case.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Internal---UK-Piercing--store-dev---31-May-2022#9]
**Actual result:**
The text Policy have to be in uppercase, for some of the policies it is coming in lower case.
![image](https://user-images.githubusercontent.com/102131636/166876117-11890313-d2e0-40e2-819d-dc1072044a0b.png)

**Expected result:**
The text policy have to be in uppercase it will be much better.

**Comment by ui-amansingh** [comment]
fixed

**Comment by sudhanshu0603** [comment]
ok, resolved
